### ISSUE TITLE
大佬，菜菜，救救

### ISSUE THREAD

**Issue by lyfto** [zhufengning/pixiv-translator#1]
那啥，大佬打扰了，我实在是有点小白，想问一下想访问的网址应该粘贴在哪？（就是api那些搞好了，然后就不知道干啥了）

**Comment by zhufengning** [comment]
点击启动之后最顶上那行字里的蓝色的“我”是可以点的
![图片](https://github.com/zhufengning/pixiv-translator/assets/22849152/81829289-1466-4694-b012-b157a2b37d86)

**Comment by zhufengning** [comment]
打开的网页里，这个“go”也是可以点的
![图片](https://github.com/zhufengning/pixiv-translator/assets/22849152/9d3fc36b-3109-4a74-a234-27a17e895c14)

**Comment by lyfto** [comment]
不是大佬，就怪不好意思的，这两步都没问题，然后呢？

**Comment by zhufengning** [comment]
输完id点go不就直接进翻译页面了吗，两千字日语，两千字中文，双语交替显示。

**Comment by zhufengning** [comment]
输完id点go不就直接进翻译页面了吗，两千字日语，两千字中文，双语交替显示。

**Comment by lyfto** [comment]
![屏幕截图(139)](https://github.com/zhufengning/pixiv-translator/assets/160275643/9a741c25-ceb0-4105-97f0-fc13cf05425a)
大佬，这大概是为啥子？
p站确实能打开，vpn端口是2080也没冲突
![image](https://github.com/zhufengning/pixiv-translator/assets/160275643/e7b31eea-c274-412f-80ad-00272dc07a29)

**Comment by lyfto** [comment]
我太弱小了，没有力量qwq

**Comment by zhufengning** [comment]
你id怎么那么长？

**Comment by zhufengning** [comment]
![图片](https://github.com/zhufengning/pixiv-translator/assets/22849152/10f713df-bc55-4932-be51-7bd5e8c0a31f)
一般是这个长度啊

**Comment by lyfto** [comment]
坏，我以前真不知道p站id，以前手机用的多

**Comment by lyfto** [comment]
![image](https://github.com/zhufengning/pixiv-translator/assets/160275643/05a1434b-dd3d-465a-9cf6-26e278536df9)
咳咳，大佬，新的问题又出现了，p站能登，这大概是怎个事？可能是我vpn的质量不行吗？

**Comment by lyfto** [comment]
啊淦，大佬，我突然理解了，顿悟了，解决了，我填了我自己的id
